### PR TITLE
Refactor the ODT parser to use KDF

### PR DESCRIPTION
**Pull request by X-m7**
### 🚨 Contributor Checklist

 - [x] I have read and followed the [Contributing guide](https://github.com/sean0x42/kauri/blob/develop/.github/CONTRIBUTING.md).
 - [x] I am merging into the appropriate branch (usually `develop`).
 - [x] I am merging from a feature/bugfix branch (not my `master` branch).
 - [x] I have run appropriate [linters](https://github.com/sean0x42/kauri/blob/develop/.github/CONTRIBUTING.md#linters) as outlined in the Contributing guide.
 - [x] I have added any major changes to `CHANGELOG.md`.

### Proposed Changes

 - Refactor the ODT parser to use KDF

❤️ Thank you for your contribution!

### CODE REVIEW

**Comment by sean0x42** [comment]
@X-m7 Travis has failed for this build. I'm on mobile so you might have to check why

**Comment by X-m7** [comment]
> @X-m7 Travis has failed for this build. I'm on mobile so you might have to check why

That's the error apparently, tried to restart the build but I got the same thing.
Screenshot_20190808_162751

**Comment by sean0x42** [comment]
Oh well, I guess just give at an hour or so and try again

**Comment by X-m7** [comment]
@sean0x42 I triggered a rebuild, seems like it works now.

**Pull request merged**
