### PR TITLE
Add save to KDF

### PR DESCRIPTION
**Pull request by sean0x42**
### 🚨 Contributor Checklist

 - [x] I have read and followed the [Contributing guide](https://github.com/sean0x42/kauri/blob/develop/.github/CONTRIBUTING.md).
 - [x] I am merging into the appropriate branch (usually `develop`).
 - [x] I am merging from a feature/bugfix branch (not my `master` branch).
 - [x] I have run appropriate [linters](https://github.com/sean0x42/kauri/blob/develop/.github/CONTRIBUTING.md#linters) as outlined in the Contributing guide.
 - [x] I have added any major changes to `CHANGELOG.md`.

### Proposed Changes

 - Add helper for saving current document
 - Add a menu option for saving document as KDF
 - Allow metadata and style reducers to handle FETCH_DOCUMENT_SUCCESS actions.
 - Fix pageStyles
 - Resolve an issue where a shorthand text node was given the type `text` instead of `Text`. Thanks @X-m7 

Still need to fix the renderer not correctly rendering documents opened from the server. But otherwise functionality exists for loading an ODT document, making simple modifications, and saving it as KDF.

❤️ Thank you for your contribution!

### CODE REVIEW

**Comment by X-m7** [comment]
Seems like there's still places where node type names aren't capitalised in the client, when just saving the sample document to KDF those are what's generated for most of the nodes. I only just noticed the capitalisation is actually inconsistent with what the KDF spec says, so that was actually a server side bug. I'll make a PR to this branch to fix that.

**Comment by sean0x42** [comment]
> ..is actually inconsistent with what the KDF spec says, so that was actually a server side bug. I'll make a PR to this branch to fix that.

@X-m7 No don't worry about that Prajna, I prefer it capitalised the way the server does it, and when I rewrite the spec it will be capitalised that way as well. In other words, the current version of the spec is wrong, not the server lol

**Comment by X-m7** [comment]
And I accidentally pushed to this branch instead, whoops

**Comment by sean0x42** [comment]
Wow, I didn't know that was possible haha

**Comment by X-m7** [comment]
Well either way it looks to me like the client is using lowercase/camelCase for most cases anyway, at least it did when I tested it, so it might be easier to just revert the previous changes you made to fix the capitalisation. Besides, it's just a prototype, right?

**Comment by sean0x42** [comment]
> Well either way it looks to me like the client is using lowercase/camelCase for most cases anyway, at least it did when I tested it, so it might be easier to just revert the previous changes you made to fix the capitalisation. Besides, it's just a prototype, right?

Alright sure, I can do that quickly now

**Comment by X-m7** [comment]
After fixing up a few more bugs in the server (will definitely be in another PR) I got saving an edited version of the sample document and loading it back to work, although after saving an error pops up with the message below. Also, is it normal for editing to only be possible after a right click?
```
Uncaught (in promise) TypeError: Cannot read property 'type' of undefined
    at Renderer.module.exports../src/renderer/render/content.tsx.Renderer.toRenderable (content.tsx:141)
    at content.tsx:158
    at Array.map (<anonymous>)
    at Renderer.module.exports../src/renderer/render/content.tsx.Renderer.renderNodeChildren (content.tsx:158)
    at m.Element [as constructor] (index.jsx:32)
    at m.H [as render] (preact.module.js:1)
    at $ (preact.module.js:1)
    at preact.module.js:1
    at x (preact.module.js:1)
    at x (preact.module.js:1)
```

**Comment by sean0x42** [comment]
Yea I believe that's because the process of saving the document is actually destructive lol. I can fix that when I get home

**Pull request merged**
